CREATE TABLE FACT.FT_TRANSPORTE (
SNAPSHOT DATE,
ID_FILIAL INT REFERENCES DIMENSION.DIM_FILIAL,
NOME_MOTORISTA VARCHAR(200),
CARRO VARCHAR(10),
PARADAS INT,
ULTIM_LOCAL VARCHAR(200),
STATUS VARCHAR(3),
QUANTI_CAIXA INT,
QUANTI_ITENS INT,
CDG_REMESSA INT,
ID_CLIENTE INT REFERENCES DIMENSION.DIM_CLIENTE,
LAT VARCHAR(15),
LONG VARCHAR(15)
)

CREATE TABLE DIMENSION.DIM_FILIAL (
	ID INT PRIMARY KEY UNIQUE,
	NOME_FILIAL VARCHAR(10),
	ENDERECO VARCHAR(200)
)

CREATE TABLE DIMENSION.DIM_CLIENTE (
	ID INT PRIMARY KEY UNIQUE,
	NOME_CLIENTE,
	ENDERECO_CLIENTE
)