CREATE TABLE FACT.FT_HR (
	MATRICULA INT,
	NOME VARCHAR(100),
	BRANCH VARCHAR(100),
	MANAGER VARCHAR(100),
	DEPARTAMENTO VARCHAR(200),
	EXPEDIENTE VARCHAR(100),
	DATA DATE,
	HORAS_PREVISTAS INT,
	HORAS_TRABALHADAS INT,
	FALTA BOOLEAN,
	MOTIVO_FALTA VARCHAR(200)
)