CREATE SCHEMA DIMENSION;
CREATE SCHEMA FACT;

CREATE TABLE DIMENSION.DIM_PROD (
	ID INT PRIMARY KEY UNIQUE,
	PROD_NAME VARCHAR(150),
	VALIDITY DATE
);
CREATE TABLE DIMENSION.DIM_STORAGE_ROOMS (
	ID INT PRIMARY KEY UNIQUE,
	ROOM_NAME VARCHAR(60),
	CAPACITY INT
);

CREATE TABLE FACT.FT_STORAGE(
	ROOM INT REFERENCES DIMENSION.DIM_STORAGE_ROOMS (ID),
	PROD_ID INT REFERENCES DIMENSION.DIM_PROD (ID),
	UNITS INT,
	BRANCH VARCHAR(4),
	SNAPSHOT TIMESTAMP
);

-- Making the validity rules

select 
	b.branch,
	a.id,
	a.prod_name,
	a.validity,
	b.units,
	b.room ,
	CASE WHEN A.VALIDITY - CURRENT_DATE <= 30 THEN 'Less than 1 month'
	WHEN A.VALIDITY - CURRENT_DATE > 30 AND A.VALIDITY - CURRENT_DATE <= 90 THEN '1 to 3 months'
	WHEN A.VALIDITY - CURRENT_DATE > 90 AND A.VALIDITY - CURRENT_DATE <= 180  THEN '3 to 6 months'
	WHEN A.VALIDITY - CURRENT_DATE > 180 AND A.VALIDITY - CURRENT_DATE <= 360 THEN '6 to 12 months'
	WHEN A.VALIDITY - CURRENT_DATE > 360 AND A.VALIDITY - CURRENT_DATE <= 720 THEN '1 to 2 years'
	ELSE 'More then 2 Years'
	END DAYS_TO_EXPIRE,
	CASE WHEN A.VALIDITY - CURRENT_DATE <= 30 THEN 1
	WHEN A.VALIDITY - CURRENT_DATE > 30 AND A.VALIDITY - CURRENT_DATE <= 90 THEN 2
	WHEN A.VALIDITY - CURRENT_DATE > 90 AND A.VALIDITY - CURRENT_DATE <= 180  THEN 3
	WHEN A.VALIDITY - CURRENT_DATE > 180 AND A.VALIDITY - CURRENT_DATE <= 360  THEN 4
	WHEN A.VALIDITY - CURRENT_DATE > 360 AND A.VALIDITY - CURRENT_DATE <= 720  THEN 5
	ELSE 6
	END ORDER_KEY,
	SNAPSHOT
from FACT.FT_STORAGE b
inner join DIMENSION.DIM_PROD a on (b.PROD_ID = a.id)
